"""Initialize ChatBI's local PostgreSQL-first development databases.

Administrator credentials are read only from the process environment or an
interactive prompt. They are never written to disk. Project-scoped passwords
are generated into the gitignored repository .env file.
"""

from __future__ import annotations

import argparse
import getpass
import os
import secrets
from pathlib import Path

import psycopg
import pymysql
from psycopg import sql


PROJECT_ROOT = Path(__file__).resolve().parents[3]
ENV_PATH = PROJECT_ROOT / ".env"
POSTGRES_SEED = PROJECT_ROOT / "database" / "postgresql" / "demo_business.sql"
MYSQL_SEED = PROJECT_ROOT / "database" / "mysql" / "demo_business.sql"


def _read_env() -> dict[str, str]:
    if not ENV_PATH.exists():
        return {}
    values: dict[str, str] = {}
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        if line and not line.lstrip().startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def _project_secrets() -> dict[str, str]:
    values = _read_env()
    reader_password = values.get("CHATBI_DEMO_POSTGRES_PASSWORD") or secrets.token_urlsafe(30)
    values.update({
        "CHATBI_META_PASSWORD": values.get("CHATBI_META_PASSWORD") or secrets.token_urlsafe(30),
        "CHATBI_DATASOURCE_SECRET_KEY": values.get("CHATBI_DATASOURCE_SECRET_KEY") or secrets.token_urlsafe(48),
        "CHATBI_RAG_SHARED_SECRET": values.get("CHATBI_RAG_SHARED_SECRET") or secrets.token_urlsafe(48),
        "CHATBI_DEMO_POSTGRES_PASSWORD": reader_password,
        "CHATBI_DEMO_MYSQL_PASSWORD": values.get("CHATBI_DEMO_MYSQL_PASSWORD") or reader_password,
        "CHATBI_BOOTSTRAP_ADMIN_PASSWORD": values.get("CHATBI_BOOTSTRAP_ADMIN_PASSWORD") or secrets.token_urlsafe(24),
        "CHATBI_BOOTSTRAP_ANALYST_PASSWORD": values.get("CHATBI_BOOTSTRAP_ANALYST_PASSWORD") or secrets.token_urlsafe(24),
    })
    values["CHATBI_DATABASE_URL"] = values.get("CHATBI_DATABASE_URL") or (
        "postgresql+psycopg://chatbi_app:"
        f"{values['CHATBI_META_PASSWORD']}@host.docker.internal:5432/chatbi_v2"
    )
    return values


def _write_env(values: dict[str, str]) -> None:
    content = "# Generated by scripts/bootstrap-local-databases.ps1; never commit.\n"
    content += "\n".join(f"{key}={value}" for key, value in values.items()) + "\n"
    temporary = ENV_PATH.with_suffix(".env.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(ENV_PATH)


def _admin_password(variable: str, prompt: str) -> str:
    value = os.environ.pop(variable, None)
    return value or getpass.getpass(prompt)


def _bootstrap_postgres(admin_password: str, values: dict[str, str], reset_demo: bool) -> tuple[int, int]:
    postgres_host = os.getenv("CHATBI_LOCAL_POSTGRES_HOST", "127.0.0.1")
    postgres_port = int(os.getenv("CHATBI_LOCAL_POSTGRES_PORT", "5432"))
    with psycopg.connect(
        host=postgres_host, port=postgres_port, dbname="postgres", user="postgres",
        password=admin_password, autocommit=True,
    ) as admin:
        with admin.cursor() as cursor:
            for role, password in (
                ("chatbi_app", values["CHATBI_META_PASSWORD"]),
                ("chatbi_reader", values["CHATBI_DEMO_POSTGRES_PASSWORD"]),
            ):
                cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role,))
                statement = "ALTER ROLE {} LOGIN PASSWORD {}" if cursor.fetchone() else "CREATE ROLE {} LOGIN PASSWORD {}"
                cursor.execute(sql.SQL(statement).format(sql.Identifier(role), sql.Literal(password)))
            cursor.execute("SELECT 1 FROM pg_database WHERE datname = 'chatbi_v2'")
            if cursor.fetchone() is None:
                cursor.execute(sql.SQL("CREATE DATABASE {} OWNER {}").format(sql.Identifier("chatbi_v2"), sql.Identifier("chatbi_app")))
            else:
                cursor.execute(sql.SQL("ALTER DATABASE {} OWNER TO {}").format(sql.Identifier("chatbi_v2"), sql.Identifier("chatbi_app")))

    with psycopg.connect(
        host=postgres_host, port=postgres_port, dbname="chatbi_v2", user="postgres",
        password=admin_password, autocommit=True,
    ) as database:
        with database.cursor() as cursor:
            # The application role must not receive CREATEROLE.  These tightly
            # scoped SECURITY DEFINER helpers are the only privileged path used
            # by managed spreadsheet imports.  Both arguments are validated
            # against application-owned identifiers before any dynamic SQL is
            # executed, and callers cannot grant access outside the matching
            # excel_<id> schema.
            cursor.execute(
                """
                CREATE SCHEMA IF NOT EXISTS chatbi_admin AUTHORIZATION postgres;
                REVOKE ALL ON SCHEMA chatbi_admin FROM PUBLIC;
                GRANT USAGE ON SCHEMA chatbi_admin TO chatbi_app;

                CREATE OR REPLACE FUNCTION chatbi_admin.provision_excel_reader(
                    role_name text,
                    role_password text,
                    schema_name text
                ) RETURNS void
                LANGUAGE plpgsql
                SECURITY DEFINER
                SET search_path = pg_catalog, pg_temp
                AS $function$
                BEGIN
                    IF role_name !~ '^chatbi_excel_[0-9a-f]{12}$'
                       OR schema_name !~ '^excel_[0-9a-f]{12}$'
                       OR substring(role_name from 14) <> substring(schema_name from 7)
                       OR role_password IS NULL
                       OR length(role_password) < 32 THEN
                        RAISE EXCEPTION 'invalid managed spreadsheet reader request';
                    END IF;
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
                        RAISE EXCEPTION 'managed spreadsheet reader already exists';
                    END IF;
                    EXECUTE format(
                        'CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION',
                        role_name,
                        role_password
                    );
                    EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', schema_name, role_name);
                    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO %I', schema_name, role_name);
                END;
                $function$;

                CREATE OR REPLACE FUNCTION chatbi_admin.drop_excel_reader(
                    role_name text,
                    schema_name text
                ) RETURNS void
                LANGUAGE plpgsql
                SECURITY DEFINER
                SET search_path = pg_catalog, pg_temp
                AS $function$
                BEGIN
                    IF role_name !~ '^chatbi_excel_[0-9a-f]{12}$'
                       OR schema_name !~ '^excel_[0-9a-f]{12}$'
                       OR substring(role_name from 14) <> substring(schema_name from 7) THEN
                        RAISE EXCEPTION 'invalid managed spreadsheet reader request';
                    END IF;
                    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
                        IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = schema_name) THEN
                            EXECUTE format(
                                'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA %I FROM %I',
                                schema_name,
                                role_name
                            );
                            EXECUTE format('REVOKE ALL PRIVILEGES ON SCHEMA %I FROM %I', schema_name, role_name);
                        END IF;
                        EXECUTE format('DROP ROLE %I', role_name);
                    END IF;
                END;
                $function$;

                REVOKE ALL ON FUNCTION chatbi_admin.provision_excel_reader(text, text, text) FROM PUBLIC;
                REVOKE ALL ON FUNCTION chatbi_admin.drop_excel_reader(text, text) FROM PUBLIC;
                GRANT EXECUTE ON FUNCTION chatbi_admin.provision_excel_reader(text, text, text) TO chatbi_app;
                GRANT EXECUTE ON FUNCTION chatbi_admin.drop_excel_reader(text, text) TO chatbi_app;

                DROP FUNCTION IF EXISTS public.chatbi_provision_excel_reader(text, text, text);
                DROP FUNCTION IF EXISTS public.chatbi_drop_excel_reader(text, text);
                """,
                prepare=False,
            )
            cursor.execute("SELECT 1 FROM information_schema.schemata WHERE schema_name = 'demo_business'")
            schema_exists = cursor.fetchone() is not None
            if reset_demo and schema_exists:
                cursor.execute("DROP SCHEMA demo_business CASCADE")
                schema_exists = False
            if not schema_exists:
                cursor.execute("CREATE SCHEMA demo_business")
                cursor.execute(POSTGRES_SEED.read_text(encoding="utf-8"), prepare=False)
            cursor.execute("GRANT CONNECT ON DATABASE chatbi_v2 TO chatbi_reader")
            cursor.execute("GRANT USAGE ON SCHEMA demo_business TO chatbi_reader")
            cursor.execute("GRANT SELECT ON ALL TABLES IN SCHEMA demo_business TO chatbi_reader")
            cursor.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA demo_business GRANT SELECT ON TABLES TO chatbi_reader")
            cursor.execute("SELECT count(*) FROM demo_business.orders")
            orders = cursor.fetchone()[0]
            cursor.execute("SELECT count(*) FROM demo_business.daily_kpi")
            kpis = cursor.fetchone()[0]
    return orders, kpis


def _bootstrap_mysql(admin_password: str, values: dict[str, str], reset_demo: bool) -> tuple[int, int]:
    connection = pymysql.connect(
        host="127.0.0.1", port=3306, user="root", password=admin_password,
        charset="utf8mb4", autocommit=True,
    )
    try:
        with connection.cursor() as cursor:
            if reset_demo:
                cursor.execute("DROP DATABASE IF EXISTS chatbi_demo_business")
            cursor.execute("CREATE DATABASE IF NOT EXISTS chatbi_demo_business CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
            cursor.execute("SELECT count(*) FROM information_schema.tables WHERE table_schema='chatbi_demo_business' AND table_name='orders'")
            if cursor.fetchone()[0] == 0:
                cursor.execute("USE chatbi_demo_business")
                for statement in MYSQL_SEED.read_text(encoding="utf-8").split(";"):
                    if statement.strip():
                        cursor.execute(statement)
            for host in ("%", "localhost"):
                parameterized_host = host.replace("%", "%%")
                cursor.execute(f"CREATE USER IF NOT EXISTS 'chatbi_reader'@'{parameterized_host}' IDENTIFIED BY %s", (values["CHATBI_DEMO_MYSQL_PASSWORD"],))
                cursor.execute(f"ALTER USER 'chatbi_reader'@'{parameterized_host}' IDENTIFIED BY %s", (values["CHATBI_DEMO_MYSQL_PASSWORD"],))
                cursor.execute(f"GRANT SELECT ON chatbi_demo_business.* TO 'chatbi_reader'@'{host}'")
            cursor.execute("FLUSH PRIVILEGES")
            cursor.execute("SELECT count(*) FROM chatbi_demo_business.orders")
            orders = cursor.fetchone()[0]
            cursor.execute("SELECT count(*) FROM chatbi_demo_business.daily_kpi")
            kpis = cursor.fetchone()[0]
    finally:
        connection.close()
    return orders, kpis


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset-demo", action="store_true", help="replace only the simulated demo schemas")
    parser.add_argument("--auth-only", action="store_true", help="add missing local application login secrets without touching databases")
    parser.add_argument(
        "--spreadsheet-helpers-only",
        action="store_true",
        help="install scoped PostgreSQL spreadsheet-reader helpers without requiring MySQL administration",
    )
    args = parser.parse_args()
    values = _project_secrets()
    if args.auth_only:
        _write_env(values)
        print("LOCAL_AUTH_CONFIGURATION=PASS")
        print("PROJECT_ENV_WRITTEN=YES SESSION_TOKEN_GENERATED=NO")
        return
    postgres_password = _admin_password("CHATBI_LOCAL_POSTGRES_ADMIN_PASSWORD", "Local PostgreSQL administrator password: ")
    if args.spreadsheet_helpers_only:
        pg_orders, pg_kpis = _bootstrap_postgres(postgres_password, values, False)
        _write_env(values)
        print("SPREADSHEET_READER_HELPERS=PASS")
        print(f"POSTGRES_ORDERS={pg_orders} POSTGRES_DAILY_KPI={pg_kpis}")
        print("PROJECT_ENV_WRITTEN=YES ADMIN_CREDENTIALS_PERSISTED=NO")
        return
    mysql_password = _admin_password("CHATBI_LOCAL_MYSQL_ADMIN_PASSWORD", "Local MySQL administrator password: ")
    pg_orders, pg_kpis = _bootstrap_postgres(postgres_password, values, args.reset_demo)
    my_orders, my_kpis = _bootstrap_mysql(mysql_password, values, args.reset_demo)
    _write_env(values)
    print("LOCAL_DATABASE_BOOTSTRAP=PASS")
    print(f"POSTGRES_ORDERS={pg_orders} POSTGRES_DAILY_KPI={pg_kpis}")
    print(f"MYSQL_ORDERS={my_orders} MYSQL_DAILY_KPI={my_kpis}")
    print("PROJECT_ENV_WRITTEN=YES ADMIN_CREDENTIALS_PERSISTED=NO")


if __name__ == "__main__":
    main()
