"""day1 core

Revision ID: 20260816_0001
Revises:
Create Date: 2026-08-17 00:05:36.244873
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '20260816_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasource',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('schema', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_workspace_id'), 'datasource', ['workspace_id'], unique=False)
    op.create_table('datasource_relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('datasource_id', sa.String(length=36), nullable=False),
    sa.Column('source_schema', sa.String(length=255), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=False),
    sa.Column('source_columns', sa.JSON(), nullable=False),
    sa.Column('target_schema', sa.String(length=255), nullable=True),
    sa.Column('target_table', sa.String(length=255), nullable=False),
    sa.Column('target_columns', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_relation_datasource_id'), 'datasource_relation', ['datasource_id'], unique=False)
    op.create_table('datasource_schema',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('datasource_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_id', 'name')
    )
    op.create_index(op.f('ix_datasource_schema_datasource_id'), 'datasource_schema', ['datasource_id'], unique=False)
    op.create_table('semantic_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('datasource_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_model_datasource_id'), 'semantic_model', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_semantic_model_workspace_id'), 'semantic_model', ['workspace_id'], unique=False)
    op.create_table('business_term',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('mapped_object', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_term_semantic_model_id'), 'business_term', ['semantic_model_id'], unique=False)
    op.create_table('datasource_table',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schema_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['datasource_schema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'name')
    )
    op.create_index(op.f('ix_datasource_table_schema_id'), 'datasource_table', ['schema_id'], unique=False)
    op.create_table('dimension',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_semantic_model_id'), 'dimension', ['semantic_model_id'], unique=False)
    op.create_table('metric',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('aggregation', sa.String(length=32), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_semantic_model_id'), 'metric', ['semantic_model_id'], unique=False)
    op.create_table('semantic_entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=False),
    sa.Column('primary_key', sa.String(length=255), nullable=False),
    sa.Column('time_dimension', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_entity_semantic_model_id'), 'semantic_entity', ['semantic_model_id'], unique=False)
    op.create_table('semantic_relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('left_entity', sa.String(length=255), nullable=False),
    sa.Column('right_entity', sa.String(length=255), nullable=False),
    sa.Column('join_type', sa.String(length=32), nullable=False),
    sa.Column('join_keys', sa.JSON(), nullable=False),
    sa.Column('cardinality', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_relation_semantic_model_id'), 'semantic_relation', ['semantic_model_id'], unique=False)
    op.create_table('semantic_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_model_id', 'version')
    )
    op.create_index(op.f('ix_semantic_version_semantic_model_id'), 'semantic_version', ['semantic_model_id'], unique=False)
    op.create_table('datasource_column',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=1536), nullable=False),
    sa.Column('data_type', sa.String(length=255), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=False),
    sa.Column('foreign_key', sa.Boolean(), nullable=False),
    sa.Column('default', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['datasource_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name')
    )
    op.create_index(op.f('ix_datasource_column_table_id'), 'datasource_column', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_column_table_id'), table_name='datasource_column')
    op.drop_table('datasource_column')
    op.drop_index(op.f('ix_semantic_version_semantic_model_id'), table_name='semantic_version')
    op.drop_table('semantic_version')
    op.drop_index(op.f('ix_semantic_relation_semantic_model_id'), table_name='semantic_relation')
    op.drop_table('semantic_relation')
    op.drop_index(op.f('ix_semantic_entity_semantic_model_id'), table_name='semantic_entity')
    op.drop_table('semantic_entity')
    op.drop_index(op.f('ix_metric_semantic_model_id'), table_name='metric')
    op.drop_table('metric')
    op.drop_index(op.f('ix_dimension_semantic_model_id'), table_name='dimension')
    op.drop_table('dimension')
    op.drop_index(op.f('ix_datasource_table_schema_id'), table_name='datasource_table')
    op.drop_table('datasource_table')
    op.drop_index(op.f('ix_business_term_semantic_model_id'), table_name='business_term')
    op.drop_table('business_term')
    op.drop_index(op.f('ix_semantic_model_workspace_id'), table_name='semantic_model')
    op.drop_index(op.f('ix_semantic_model_datasource_id'), table_name='semantic_model')
    op.drop_table('semantic_model')
    op.drop_index(op.f('ix_datasource_schema_datasource_id'), table_name='datasource_schema')
    op.drop_table('datasource_schema')
    op.drop_index(op.f('ix_datasource_relation_datasource_id'), table_name='datasource_relation')
    op.drop_table('datasource_relation')
    op.drop_index(op.f('ix_datasource_workspace_id'), table_name='datasource')
    op.drop_table('datasource')
    op.drop_table('workspace')
    # ### end Alembic commands ###
