import { useState, type FormEvent } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { semanticApi } from '../api/semantic';
import { useDatasources, useSemanticModels } from '../hooks/useData';
import { ErrorNotice, Field, FormActions, Loading, Modal, PageHeading, StatusBadge } from '../components/UI';
import type { SemanticModelInput } from '../types/api';

export function SemanticModelsPage() {
  const models = useSemanticModels(); const sources = useDatasources(); const client = useQueryClient(); const navigate = useNavigate();
  const [showCreate, setShowCreate] = useState(false); const [search, setSearch] = useState('');
  const [form, setForm] = useState<SemanticModelInput>({ name: '', description: '', datasource_id: '' });
  const create = useMutation({ mutationFn: semanticApi.create, onSuccess: (model) => { client.invalidateQueries({ queryKey: ['semantic-models'] }); setShowCreate(false); navigate(`/semantic-models/${model.id}`); } });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(form); };
  const filtered = (models.data ?? []).filter((model) => model.name.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading title="语义模型" description="用统一的业务、度量、口径和关系组织数据，让自然语言查询结果更准确。" actions={<button className="button primary" data-testid="create-model" onClick={() => setShowCreate(true)}>＋ 新建语义模型</button>} /><ErrorNotice error={models.error ?? sources.error}/><div className="filterbar"><input aria-label="搜索语义模型" placeholder="⌕  搜索模型名称" value={search} onChange={(e) => setSearch(e.target.value)}/><span><span className="badge badge-published">{(models.data ?? []).filter((x) => x.status === 'PUBLISHED').length} 个已发布</span>　<span className="badge badge-draft">{(models.data ?? []).filter((x) => x.status === 'DRAFT').length} 个草稿</span></span></div>{models.isLoading ? <Loading/> : <div className="model-grid">{filtered.map((model) => <Link to={`/semantic-models/${model.id}`} className="model-card" key={model.id} data-testid="semantic-model-card"><div className="model-card-head"><span className="model-icon">MOL</span><div><h2>{model.name}</h2><p>{model.description || '尚未填写模型描述'}</p></div><StatusBadge status={model.status}/></div><div className="model-stats"><span><strong>{model.entities?.length ?? 0}</strong><small>实体</small></span><span><strong>{model.metrics?.length ?? 0}</strong><small>度量</small></span><span><strong>{model.relationships?.length ?? 0}</strong><small>关系</small></span></div><footer>版本 {model.version ?? 'v0.1.0'}<b>打开编辑器 →</b></footer></Link>)}</div>}{!models.isLoading && filtered.length === 0 && <div className="empty-card"><span>模</span><h2>还没有语义模型</h2><p>关联数据源并定义业务实体、指标和维度。</p><button className="button primary" onClick={() => setShowCreate(true)}>新建语义模型</button></div>}{showCreate && <Modal title="新建语义模型" onClose={() => setShowCreate(false)}><form className="form-grid" onSubmit={submit}><Field label="模型名称"><input name="model-name" required placeholder="例如：新能源经营分析" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></Field><Field label="数据源"><select name="datasource" required value={form.datasource_id} onChange={(e) => setForm({ ...form, datasource_id: e.target.value })}><option value="">请选择数据源</option>{sources.data?.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></Field><Field label="描述"><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></Field><ErrorNotice error={create.error}/><FormActions busy={create.isPending} onCancel={() => setShowCreate(false)} submitLabel="创建并打开编辑器"/></form></Modal>}</>;
}
